#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR/rish_shizuku.dex"

if [ ! -f "$DEX" ]; then
  DEX="/data/data/com.termux/files/usr/bin/rish_shizuku.dex"
fi

if [ $(getprop ro.build.version.sdk 2>/dev/null || echo 0) -ge 34 ]; then
  if [ -w "$DEX" ]; then
    chmod 400 "$DEX" 2>/dev/null || chmod 444 "$DEX" 2>/dev/null
  fi
fi

# Set Application ID for Termux & Library Path
export RISH_APPLICATION_ID="com.termux"
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib:/data/data/com.termux/files/usr/bin:$LD_LIBRARY_PATH"

PREFIX_DIR="/data/data/com.termux/files/usr"
exec /system/bin/app_process -Djava.library.path="$PREFIX_DIR/lib:$PREFIX_DIR/bin" -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
